### Log4MT - A plugin for Movable Type.
# Copyright (c) 2007, Jay Allen
# This program is distributed under the terms of the
# GNU General Public License, version 2.
# $Id$
name: Log4MT
key: Log4MT
id: Log4MT
version: 1.7.4
author_name: "Jay Allen, Endevver LLC"
author_link: http://endevver.com/
description: The Log4MT plugin enhances Movable Type with the fantastic and ultra-powerful Log4Perl logging framework.
plugin_link: http://github.com/endevver/mt-plugin-log4mt
doc_link:  https://github.com/endevver/mt-plugin-log4mt/blob/master/README.markdown

init: $Log4MT::Log4MT::init

config_settings:
    Log4MTConfig:
        default: log4mt.conf
        path: 1

callbacks:
    post_init: $Log4MT::Log4MT::post_init
    init_request: $Log4MT::Log4MT::init_request
    template_param: $Log4MT::Log4MT::show_template_params

tags:
    block:
        LoggerBlock: $Log4MT::Log4MT::hdlr_logger
    function:
        Logger: $Log4MT::Log4MT::hdlr_logger

